=== DianaM411/examenLM3/EJERCICIO1/reglas.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified">

<!-- definition of simple elements -->
<xs:element name="fecha" type="xs:date"/>
<xs:element name="tempMax" type="xs:decimal"/>
<xs:element name="tempMin" type="xs:decimal"/>
<xs:element name="probLluvia" type="xs:string"/>
<xs:element name="avisoRiesgo">
    <xs:simpleType>
        <xs:restriction base="xs:string">
        <xs:enumeration value="viento"/>
        <xs:enumeration value="nieve"/>
        <xs:enumeration value="tormentas"/>
        <xs:enumeration value="huracan"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>


<!-- definition of complex elements -->
<xs:element name="prediccion">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="fecha"/>
      <xs:element ref="tempMax"/>
      <xs:element ref="tempMin"/>
      <xs:element ref="probLluvia"/>
      <xs:element ref="avisoRiesgo" maxOccurs="10" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="meteo">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="comunidad" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="comunidad">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="provincia" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="nombreComunidad" type="xs:string" use="required"/>
  </xs:complexType>
</xs:element>

<xs:element name="provincia">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="poblacion" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="nombreProvincia" type="xs:string" use="required"/>
  </xs:complexType>
</xs:element>

<xs:element name="poblacion">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="prediccion" minOccurs="1" maxOccurs="100"/>
    </xs:sequence>
    <xs:attribute name="nombrePoblacion" type="xs:string" use="required"/>
  </xs:complexType>
</xs:element>

</xs:schema>

=== DianaM411/examenLM3/EJERCICIO1/meteo.xml
<?xml version="1.0" encoding="UTF-8"?>

<meteo xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com reglas.xsd">

   <comunidad nombreComunidad ="Madrid">
      <provincia nombreProvincia ="Madrid">
         <poblacion nombrePoblacion ="Alcobendas">

            <prediccion> 
            <fecha>2022-03-01</fecha>
            <tempMax>25</tempMax>
            <tempMin>15</tempMin>
            <probLluvia>20</probLluvia>
            </prediccion>

            <prediccion> 
            <fecha>2022-03-02</fecha>
            <tempMax>30</tempMax>
            <tempMin>21</tempMin>
            <probLluvia>0</probLluvia>
            </prediccion>

         </poblacion>
      </provincia>
   </comunidad>

</meteo>

=== DianaM411/examenLM3/meteo.xml
<?xml version="1.0" encoding="UTF-8"?>
<meteo xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com reglas.xsd">

<poblacion>

   <prediccion> 
    <fecha></fecha>
    <tempMax></tempMax>
    <tempMin></tempMin>
    <probLluvia></probLluvia>
    <avisoRiesgo></avisoRiesgo>
   </prediccion>

</poblacion>

</meteo>
